unit TestUConexao;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, FireDac.comp.client, UConexao;

type
  // Test methods for class TConexao

  TestTConexao = class(TTestCase)
  strict private
    FConexao: TConexao;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published

  private // colocado private para não aparecer nos testes.
    procedure TestExecute;
  end;

implementation

procedure TestTConexao.SetUp;
begin
  FConexao := TConexao.Create;
end;

procedure TestTConexao.TearDown;
begin
  FConexao.Free;
  FConexao := nil;
end;

procedure TestTConexao.TestExecute;
var
  ReturnValue: Boolean;
  query: TFDCommand;
begin

  try
    assert(TConexao.Instance.Execute
      (' insert into funcionario (id, nome, cpf, salario) values (:id, :nome, :cpf, :salario)',
      TConexao.Instance.NewParams(['id', 'nome', 'cpf', 'salario'],
      [TConexao.Instance.GetGenId('funcionario_gen'), 'joano', '123',
      5000])) > 0);
  finally
    freeAndNil(query);
  end;

end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTConexao.Suite);
ReportMemoryLeaksOnShutdown := true;

end.
