unit untCalculoImpostoTest;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.Classes, System.SysUtils, untCalculoImposto;

type
  // Test methods for class TImpostoA

  TestTImpostoA = class(TTestCase)
  strict private
    FImpostoA: TImpostoA;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestfcCalcular;
  end;
  // Test methods for class TImpostoB

  TestTImpostoB = class(TTestCase)
  strict private
    FImpostoB: TImpostoB;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestfcCalcular;
  end;
  // Test methods for class TImpostoC

  TestTImpostoC = class(TTestCase)
  strict private
    FImpostoC: TImpostoC;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestfcCalcular;
  end;

implementation

procedure TestTImpostoA.SetUp;
begin
  FImpostoA := TImpostoA.Create;
  FImpostoA.BaseCalculo := 1000;
end;

procedure TestTImpostoA.TearDown;
begin
  FImpostoA.Free;
  FImpostoA := nil;
end;

procedure TestTImpostoA.TestfcCalcular;
var
  ReturnValue: Double;
begin
  ReturnValue := FImpostoA.fcCalcular;
  // TODO: Validate method results

  CheckEquals(-300, ReturnValue);
end;

procedure TestTImpostoB.SetUp;
begin
  FImpostoB := TImpostoB.Create;
  FImpostoB.ImpostoA := TImpostoA.Create;
  FImpostoB.ImpostoA.BaseCalculo := 1000;
end;

procedure TestTImpostoB.TearDown;
begin
  FImpostoB.Free;
  FImpostoB := nil;
end;

procedure TestTImpostoB.TestfcCalcular;
var
  ReturnValue: Double;
begin
  ReturnValue := FImpostoB.fcCalcular;
  // TODO: Validate method results

  CheckEquals(-315, ReturnValue);
end;

procedure TestTImpostoC.SetUp;
begin
  FImpostoC := TImpostoC.Create;
  FImpostoC.ImpostoB := TImpostoB.Create;
  FImpostoC.ImpostoB.ImpostoA := TImpostoA.Create;
  FImpostoC.ImpostoB.ImpostoA.BaseCalculo := 1000;
end;

procedure TestTImpostoC.TearDown;
begin
  FImpostoC.Free;
  FImpostoC := nil;
end;

procedure TestTImpostoC.TestfcCalcular;
var
  ReturnValue: Double;
begin
  ReturnValue := FImpostoC.fcCalcular;
  // TODO: Validate method results

  CheckEquals(-615, ReturnValue);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTImpostoA.Suite);
  RegisterTest(TestTImpostoB.Suite);
  RegisterTest(TestTImpostoC.Suite);
end.

