unit Theos.Api.Pessoa.Test;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Theos.Api.Pessoa, Theos.Api.Calculadora, System.SysUtils,
  System.Math;

type
  // Test methods for class TPessoa

  TPessoaTest = class(TTestCase)
  strict private
    //FPessoa: TPessoa;
    const
      SALARIO: Double = 1000;
      VALOR_ESPERADO_PARA_INSS: Double = 80;
      VALOR_POR_DEPENDENTE: Double = 100;
      QUANTOS_DEPENDENTES: Integer = 2;
      VALOR_ESPERADO_PARA_BASE_IR: Double = 800;
      VALOR_BASE_IR: Double = 800;
      VALOR_ESPERADO_PARA_VALOR_IR: Double = 120;

  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    //procedure TestValidarCPF;
    procedure TestCalcularINSS;
    procedure TestCalcularBaseIR;
    procedure TestCalcularIR;

  end;

implementation

procedure TPessoaTest.SetUp;
begin

end;

procedure TPessoaTest.TearDown;
begin

end;

procedure TPessoaTest.TestCalcularINSS;
var
  Returno: Double;
begin
  try
    Returno := TPessoa.Imposto.CalcularINSS(SALARIO, QUANTOS_DEPENDENTES > 0);
  except
    on E: Exception do
    begin
      Check(True, 'Erro ao Calcular INSS: ' + e.Message);
      Exit;
    end;
  end;
  CheckEquals(VALOR_ESPERADO_PARA_INSS, Returno);
end;

procedure TPessoaTest.TestCalcularBaseIR;
var
  Returno: Double;
begin
  try
    Returno := TPessoa.Imposto.CalcularBaseIR(SALARIO, QUANTOS_DEPENDENTES);
  except
    on E: Exception do
    begin
      Check(True, 'Erro ao Calcular Base IR: ' + e.Message);
      Exit;
    end;
  end;
  CheckEquals(VALOR_ESPERADO_PARA_BASE_IR, Returno);
end;

procedure TPessoaTest.TestCalcularIR;
var
  Returno: Double;
begin
  try
    Returno := TPessoa.Imposto.CalcularIR(VALOR_BASE_IR);
  except
    on E: Exception do
    begin
      Check(True, 'Erro ao Calcular Valor IR: ' + e.Message);
      Exit;
    end;
  end;
  CheckEquals(VALOR_ESPERADO_PARA_VALOR_IR, Returno);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TPessoaTest.Suite);
end.

