CREATE TABLE FUNCIONARIO (
    CODIGO int NOT NULL,
    NOME varchar(255) NOT NULL,
    CPF varchar(11) NOT NULL,
    SALARIO float NOT NULL,
    PRIMARY KEY(CODIGO)
);

CREATE TABLE DEPENDENTE (
    CODIGO int NOT NULL,
    FUNCIONARIO int NOT NULL,
    NOME varchar(255) NOT NULL,
    ISCALCULAIR Char NOT NULL,
    ISCALCULAINSS Char NOT NULL,
    PRIMARY KEY(CODIGO),
    FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIO(CODIGO)
);
