SET SQL DIALECT 3;
SET NAMES WIN1252;

CREATE DATABASE 'C:\DB.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;

CREATE GENERATOR GEN_DEPENDENTE START WITH 0 INCREMENT BY 1;
CREATE GENERATOR GEN_FUNCIONARIO START WITH 0 INCREMENT BY 1;

CREATE TABLE FUNCIONARIO (
    ID       INTEGER NOT NULL,
    NOME     VARCHAR(100),
    SALARIO  NUMERIC(18,2)
);
ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID);

CREATE TABLE DEPENDENTE (
    ID              INTEGER NOT NULL,
    IDFUNCIONARIO   INTEGER,
    NOME            VARCHAR(100),
    ISCALCULARIR    SMALLINT,
    ISCALCULARINSS  SMALLINT
);
ALTER TABLE DEPENDENTE ADD CONSTRAINT PK_DEPENDENTE PRIMARY KEY (ID);
ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_1 FOREIGN KEY (IDFUNCIONARIO)
                       REFERENCES FUNCIONARIO (ID) ON DELETE CASCADE ON UPDATE CASCADE;


