/******************************************************************************/
/***         Generated by IBExpert 2020.4.21.2 17/03/2022 21:08:39          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Program Files\Firebird\Firebird_2_5\WOW64\fbclient.dll';

CREATE DATABASE 'C:\Projetos\ProvaEmerson\Exercicio_2_Cad_Funcionario\SistemaCalculaImposto\exe\Base\BANCO.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_DEPENDENTE_ID;
SET GENERATOR GEN_DEPENDENTE_ID TO 0;

CREATE GENERATOR GEN_FUNCIONARIO_ID;
SET GENERATOR GEN_FUNCIONARIO_ID TO 0;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE DEPENDENTE (
    CODIGO              INTEGER NOT NULL,
    CODIGO_FUNCIONARIO  INTEGER NOT NULL,
    NOME                VARCHAR(100) NOT NULL,
    CALCULARINSS        SMALLINT NOT NULL,
    CALCULARIR          SMALLINT NOT NULL
);

CREATE TABLE FUNCIONARIO (
    CODIGO   INTEGER NOT NULL,
    NOME     VARCHAR(100) NOT NULL,
    CPF      VARCHAR(20) NOT NULL,
    SALARIO  NUMERIC(15,2) NOT NULL
);



/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE DEPENDENTE ADD CONSTRAINT PK_DEPENDENTE PRIMARY KEY (CODIGO);
ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (CODIGO);


/******************************************************************************/
/***                              Foreign keys                              ***/
/******************************************************************************/

ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_FUNCIONARIO FOREIGN KEY (CODIGO_FUNCIONARIO) REFERENCES FUNCIONARIO (CODIGO);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: DEPENDENTE_BI */
CREATE TRIGGER DEPENDENTE_BI FOR DEPENDENTE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.codigo is null) then
    new.codigo = gen_id(gen_dependente_id,1);
end
^

/* Trigger: FUNCIONARIO_BI */
CREATE TRIGGER FUNCIONARIO_BI FOR FUNCIONARIO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.codigo is null) then
    new.codigo = gen_id(gen_funcionario_id,1);
end
^
SET TERM ; ^

