/******************************************************************************/
/****        Generated by IBExpert 2015.12.21.1 16/07/2020 15:15:27        ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES ISO8859_1;

CREATE DATABASE 'C:\EXERCICIO2_ENTIDADES_CALCULO.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 8192
DEFAULT CHARACTER SET ISO8859_1 COLLATION ISO8859_1;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_CADDEPENDENTE;
SET GENERATOR GEN_CADDEPENDENTE TO 0;

CREATE GENERATOR GEN_CADFUNCIONARIO;
SET GENERATOR GEN_CADFUNCIONARIO TO 0;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE CADDEPENDENTE (
    ID_DEPENDENTE   INTEGER NOT NULL,
    NOME            VARCHAR(255) NOT NULL,
    ISCALCULAIR     SMALLINT NOT NULL,
    ISCALCULAINSS   SMALLINT NOT NULL,
    ID_FUNCIONARIO  INTEGER NOT NULL
);

CREATE TABLE CADFUNCIONARIO (
    ID_FUNCIONARIO  INTEGER NOT NULL,
    NOME            VARCHAR(255) NOT NULL,
    CPF             VARCHAR(11) NOT NULL,
    SALARIO         NUMERIC(15,2) NOT NULL
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE CADDEPENDENTE ADD CONSTRAINT PK_CADDEPENDENTE PRIMARY KEY (ID_DEPENDENTE);
ALTER TABLE CADFUNCIONARIO ADD CONSTRAINT PK_CADFUNCIONARIO PRIMARY KEY (ID_FUNCIONARIO);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE CADDEPENDENTE ADD CONSTRAINT FK_CADDEPENDENTE_CADFUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES CADFUNCIONARIO (ID_FUNCIONARIO) ON DELETE CASCADE;
