--create database MATH_NOVO GO

CREATE TABLE FUNCIONARIO 
(
 CPF   VARCHAR(14) PRIMARY KEY NOT NULL, 
 NOME  VARCHAR(40) NOT NULL,
 SALARIOLIQUI FLOAT,
 SALARIOBRUTO FLOAT 
)
GO

CREATE TABLE DEPENDENTE
( 
 NOME         VARCHAR(40) NOT NULL,
 CPF_FUNC     VARCHAR(14) NOT NULL,
 CALCULARIR   VARCHAR(1)  NOT NULL,
 CALCULARINSS VARCHAR(1)  NOT NULL,
 CONSTRAINT FK_CPF_FUNC FOREIGN KEY (CPF_FUNC) REFERENCES FUNCIONARIO (CPF) 
)
GO