unit uOperacoesTest;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, uOperacoes;

type
  // Test methods for class TOperacoes

  TestTOperacoes = class(TTestCase)
  strict private
    FOperacoes: TOperacoes;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestcalcularImpostoA;
    procedure TestcalcularImpostoB;
    procedure TestcalcularImpostoC;
  end;

implementation

uses
  System.SysUtils;

procedure TestTOperacoes.SetUp;
begin
  FOperacoes := TOperacoes.Create;
end;

procedure TestTOperacoes.TearDown;
begin
  FOperacoes.Free;
  FOperacoes := nil;
end;

procedure TestTOperacoes.TestcalcularImpostoA;
var
  ReturnValue: Double;
  baseCalculo: Double;
  dResultadoEsperado: Double;
begin
  baseCalculo := 18655;
  dResultadoEsperado := 3231;
  ReturnValue := FOperacoes.calcularImpostoA(baseCalculo);
  CheckEquals(ReturnValue, dResultadoEsperado, 'Esperado: '+
    FloatToStr(dResultadoEsperado)+' / Retorno: '+FloatToStr(ReturnValue));
end;

procedure TestTOperacoes.TestcalcularImpostoB;
var
  ReturnValue: Double;
  baseCalculo: Double;
  dResultadoEsperado: Double;
begin
  baseCalculo := 18655;
  dResultadoEsperado := 3216;
  ReturnValue := FOperacoes.calcularImpostoB(baseCalculo);
  CheckEquals(ReturnValue, dResultadoEsperado, 'Esperado: '+
    FloatToStr(dResultadoEsperado)+' / Retorno: '+FloatToStr(ReturnValue));
end;

procedure TestTOperacoes.TestcalcularImpostoC;
var
  ReturnValue: Double;
  baseCalculo: Double;
  dResultadoEsperado: Double;
begin
  baseCalculo := 18655;
  dResultadoEsperado := 6447;
  ReturnValue := FOperacoes.calcularImpostoC(baseCalculo);
  CheckEquals(ReturnValue, dResultadoEsperado, 'Esperado: '+
    FloatToStr(dResultadoEsperado)+' / Retorno: '+FloatToStr(ReturnValue));
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTOperacoes.Suite);
end.

