INSERT INTO PESSOA (ID, NOME, CPF) VALUES (GEN_ID(gen_pessoa_id, 1), 'MATHEUS', '12392279811')

INSERT INTO FUNCIONARIO VALUES (2, 4, 2000)

INSERT INTO dependente VALUES (2, 'S', 'S', 3, 1)

SELECT * FROM PESSOA

SELECT * FROM FUNCIONARIO


SELECT PESSOA.NOME
     , PESSOA.CPF
     , FUNCIONARIO.SALARIO
  FROM FUNCIONARIO FUNCIONARIO
  JOIN PESSOA PESSOA
    ON PESSOA.ID = FUNCIONARIO.ID_PESSOA

SELECT PESSOA.NOME
     , PESSOA.CPF
     , DEPENDENTE.CALCULA_IR
     , DEPENDENTE.CALCULA_INSS
  FROM DEPENDENTE DEPENDENTE
  JOIN PESSOA PESSOA
    ON PESSOA.ID = DEPENDENTE.ID_PESSOA
  JOIN FUNCIONARIO FUNCIONARIO
    ON FUNCIONARIO.ID = DEPENDENTE.ID_FUNCIONARIO
